with open('hexstrike_server.py', encoding='utf-8') as f:
    content = f.read()

patches = []

# --- smbmap ---
patches.append((
    '        command = f"smbmap -H {target}"\n\n'
    '        if username:\n'
    '            command += f" -u {username}"\n\n'
    '        if password:\n'
    '            command += f" -p {password}"\n\n'
    '        if domain:\n'
    '            command += f" -d {domain}"\n\n'
    '        if additional_args:\n'
    '            command += f" {additional_args}"\n\n'
    '        logger.info(f"🔍 Starting SMBMap: {target}")\n'
    '        result = execute_command(command)\n'
    '        logger.info(f"📊 SMBMap completed for {target}")\n'
    '        return jsonify(result)',
    '        if not _validate_target(target):\n'
    '            return jsonify({"error": "invalid target"}), 400\n'
    '        if additional_args and _SHELL_META_RE.search(additional_args):\n'
    '            return jsonify({"error": "invalid additional_args"}), 400\n\n'
    '        cmd: list[str] = ["smbmap", "-H", target]\n'
    '        if username:\n'
    '            cmd += ["-u", username]\n'
    '        if password:\n'
    '            cmd += ["-p", password]\n'
    '        if domain:\n'
    '            cmd += ["-d", domain]\n'
    '        if additional_args:\n'
    '            cmd += additional_args.split()\n\n'
    '        logger.info("Starting SMBMap: %s", target)\n'
    '        result = execute_command(cmd)\n'
    '        logger.info("SMBMap completed for %s", target)\n'
    '        return jsonify(result)'
))

# --- rustscan ---
patches.append((
    '        command = f"rustscan -a {target} --ulimit {ulimit} -b {batch_size} -t {timeout}"\n\n'
    '        if ports:\n'
    '            command += f" -p {ports}"\n\n'
    '        if scripts:\n'
    '            command += f" -- -sC -sV"\n\n'
    '        if additional_args:\n'
    '            command += f" {additional_args}"\n\n'
    '        logger.info(f"⚡ Starting Rustscan: {target}")\n'
    '        result = execute_command(command)\n'
    '        logger.info(f"📊 Rustscan completed for {target}")\n'
    '        return jsonify(result)',
    '        if not _validate_target(target):\n'
    '            return jsonify({"error": "invalid target"}), 400\n'
    '        if ports and not _PORT_RE.match(str(ports)):\n'
    '            return jsonify({"error": "invalid ports"}), 400\n'
    '        if additional_args and _SHELL_META_RE.search(additional_args):\n'
    '            return jsonify({"error": "invalid additional_args"}), 400\n\n'
    '        cmd: list[str] = ["rustscan", "-a", target, "--ulimit", str(ulimit), "-b", str(batch_size), "-t", str(timeout)]\n'
    '        if ports:\n'
    '            cmd += ["-p", str(ports)]\n'
    '        if scripts:\n'
    '            cmd += ["--", "-sC", "-sV"]\n'
    '        if additional_args:\n'
    '            cmd += additional_args.split()\n\n'
    '        logger.info("Starting Rustscan: %s", target)\n'
    '        result = execute_command(cmd)\n'
    '        logger.info("Rustscan completed for %s", target)\n'
    '        return jsonify(result)'
))

# --- masscan ---
patches.append((
    '        command = f"masscan {target} -p{ports} --rate={rate}"\n\n'
    '        if interface:\n'
    '            command += f" -e {interface}"\n\n'
    '        if router_mac:\n'
    '            command += f" --router-mac {router_mac}"\n\n'
    '        if source_ip:\n'
    '            command += f" --source-ip {source_ip}"\n\n'
    '        if banners:\n'
    '            command += " --banners"\n\n'
    '        if additional_args:\n'
    '            command += f" {additional_args}"\n\n'
    '        logger.info(f"🚀 Starting Masscan: {target} at rate {rate}")\n'
    '        result = execute_command(command)\n'
    '        logger.info(f"📊 Masscan completed for {target}")\n'
    '        return jsonify(result)',
    '        if not _validate_target(target):\n'
    '            return jsonify({"error": "invalid target"}), 400\n'
    '        if not _PORT_RE.match(str(ports)):\n'
    '            return jsonify({"error": "invalid ports"}), 400\n'
    '        if additional_args and _SHELL_META_RE.search(additional_args):\n'
    '            return jsonify({"error": "invalid additional_args"}), 400\n\n'
    '        cmd: list[str] = ["masscan", target, f"-p{ports}", f"--rate={rate}"]\n'
    '        if interface:\n'
    '            cmd += ["-e", interface]\n'
    '        if router_mac:\n'
    '            cmd += ["--router-mac", router_mac]\n'
    '        if source_ip and _validate_target(source_ip):\n'
    '            cmd += ["--source-ip", source_ip]\n'
    '        if banners:\n'
    '            cmd.append("--banners")\n'
    '        if additional_args:\n'
    '            cmd += additional_args.split()\n\n'
    '        logger.info("Starting Masscan: %s at rate %s", target, rate)\n'
    '        result = execute_command(cmd)\n'
    '        logger.info("Masscan completed for %s", target)\n'
    '        return jsonify(result)'
))

# --- nmap-advanced ---
patches.append((
    '        command = f"nmap {scan_type} {target}"\n\n'
    '        if ports:\n'
    '            command += f" -p {ports}"\n\n'
    '        if stealth:\n'
    '            command += " -T2 -f --mtu 24"\n'
    '        else:\n'
    '            command += f" -{timing}"\n\n'
    '        if os_detection:\n'
    '            command += " -O"\n\n'
    '        if version_detection:\n'
    '            command += " -sV"\n\n'
    '        if aggressive:\n'
    '            command += " -A"\n\n'
    '        if nse_scripts:\n'
    '            command += f" --script={nse_scripts}"\n'
    '        elif not aggressive:  # Default useful scripts if not aggressive\n'
    '            command += " --script=default,discovery,safe"\n\n'
    '        if additional_args:\n'
    '            command += f" {additional_args}"\n\n'
    '        logger.info(f"🔍 Starting Advanced Nmap: {target}")\n'
    '        result = execute_command(command)\n'
    '        logger.info(f"📊 Advanced Nmap completed for {target}")\n'
    '        return jsonify(result)',
    '        if not _validate_target(target):\n'
    '            return jsonify({"error": "invalid target"}), 400\n'
    '        if ports and not _PORT_RE.match(str(ports)):\n'
    '            return jsonify({"error": "invalid ports"}), 400\n'
    '        if additional_args and _SHELL_META_RE.search(additional_args):\n'
    '            return jsonify({"error": "invalid additional_args"}), 400\n\n'
    '        cmd: list[str] = ["nmap", scan_type, target]\n'
    '        if ports:\n'
    '            cmd += ["-p", str(ports)]\n'
    '        if stealth:\n'
    '            cmd += ["-T2", "-f", "--mtu", "24"]\n'
    '        else:\n'
    '            cmd.append(f"-{timing}")\n'
    '        if os_detection:\n'
    '            cmd.append("-O")\n'
    '        if version_detection:\n'
    '            cmd.append("-sV")\n'
    '        if aggressive:\n'
    '            cmd.append("-A")\n'
    '        if nse_scripts:\n'
    '            cmd.append(f"--script={nse_scripts}")\n'
    '        elif not aggressive:\n'
    '            cmd.append("--script=default,discovery,safe")\n'
    '        if additional_args:\n'
    '            cmd += additional_args.split()\n\n'
    '        logger.info("Starting Advanced Nmap: %s", target)\n'
    '        result = execute_command(cmd)\n'
    '        logger.info("Advanced Nmap completed for %s", target)\n'
    '        return jsonify(result)'
))

# --- autorecon ---
patches.append((
    '        command = f"autorecon {target} -o {output_dir} --heartbeat {heartbeat} --timeout {timeout}"\n\n'
    '        if port_scans != "default":\n'
    '            command += f" --port-scans {port_scans}"\n\n'
    '        if service_scans != "default":\n'
    '            command += f" --service-scans {service_scans}"\n\n'
    '        if additional_args:\n'
    '            command += f" {additional_args}"\n\n'
    '        logger.info(f"🔄 Starting AutoRecon: {target}")\n'
    '        result = execute_command(command)\n'
    '        logger.info(f"📊 AutoRecon completed for {target}")\n'
    '        return jsonify(result)',
    '        if not _validate_target(target):\n'
    '            return jsonify({"error": "invalid target"}), 400\n'
    '        if not _validate_path(output_dir):\n'
    '            return jsonify({"error": "invalid output_dir"}), 400\n'
    '        if additional_args and _SHELL_META_RE.search(additional_args):\n'
    '            return jsonify({"error": "invalid additional_args"}), 400\n\n'
    '        cmd: list[str] = ["autorecon", target, "-o", output_dir, "--heartbeat", str(heartbeat), "--timeout", str(timeout)]\n'
    '        if port_scans != "default":\n'
    '            cmd += ["--port-scans", port_scans]\n'
    '        if service_scans != "default":\n'
    '            cmd += ["--service-scans", service_scans]\n'
    '        if additional_args:\n'
    '            cmd += additional_args.split()\n\n'
    '        logger.info("Starting AutoRecon: %s", target)\n'
    '        result = execute_command(cmd)\n'
    '        logger.info("AutoRecon completed for %s", target)\n'
    '        return jsonify(result)'
))

for old, new in patches:
    if old not in content:
        print(f"NOT FOUND: {repr(old[:80])}")
    else:
        content = content.replace(old, new, 1)
        print(f"Patched OK")

with open('hexstrike_server.py', 'w', encoding='utf-8') as f:
    f.write(content)
print("Batch 4a done")
