with open('hexstrike_server.py', encoding='utf-8') as f:
    content = f.read()

patches = []

# --- enum4linux-ng ---
patches.append((
    '        command = f"enum4linux-ng {target}"\n\n'
    '        if username:\n'
    '            command += f" -u {username}"\n\n'
    '        if password:\n'
    '            command += f" -p {password}"\n\n'
    '        if domain:\n'
    '            command += f" -d {domain}"\n\n'
    '        # Add specific enumeration options\n'
    '        enum_options = []\n'
    '        if shares:\n'
    '            enum_options.append("S")\n'
    '        if users:\n'
    '            enum_options.append("U")\n'
    '        if groups:\n'
    '            enum_options.append("G")\n'
    '        if policy:\n'
    '            enum_options.append("P")\n\n'
    '        if enum_options:\n'
    '            command += f" -A {\',\'.join(enum_options)}"\n\n'
    '        if additional_args:\n'
    '            command += f" {additional_args}"\n\n'
    '        logger.info(f"🔍 Starting Enum4linux-ng: {target}")\n'
    '        result = execute_command(command)\n'
    '        logger.info(f"📊 Enum4linux-ng completed for {target}")\n'
    '        return jsonify(result)',
    '        if not _validate_target(target):\n'
    '            return jsonify({"error": "invalid target"}), 400\n'
    '        if additional_args and _SHELL_META_RE.search(additional_args):\n'
    '            return jsonify({"error": "invalid additional_args"}), 400\n\n'
    '        cmd: list[str] = ["enum4linux-ng", target]\n'
    '        if username:\n'
    '            cmd += ["-u", username]\n'
    '        if password:\n'
    '            cmd += ["-p", password]\n'
    '        if domain:\n'
    '            cmd += ["-d", domain]\n'
    '        enum_options = []\n'
    '        if shares:\n'
    '            enum_options.append("S")\n'
    '        if users:\n'
    '            enum_options.append("U")\n'
    '        if groups:\n'
    '            enum_options.append("G")\n'
    '        if policy:\n'
    '            enum_options.append("P")\n'
    '        if enum_options:\n'
    '            cmd += ["-A", ",".join(enum_options)]\n'
    '        if additional_args:\n'
    '            cmd += additional_args.split()\n\n'
    '        logger.info("Starting Enum4linux-ng: %s", target)\n'
    '        result = execute_command(cmd)\n'
    '        logger.info("Enum4linux-ng completed for %s", target)\n'
    '        return jsonify(result)'
))

# --- rpcclient (uses echo pipe — replace with file-based stdin approach) ---
patches.append((
    '        # Create command sequence\n'
    '        command_sequence = commands.replace(";", "\\n")\n\n'
    '        command = f"echo -e \'{command_sequence}\' | rpcclient {auth_string} {target}"\n\n'
    '        if additional_args:\n'
    '            command += f" {additional_args}"\n\n'
    '        logger.info(f"🔍 Starting rpcclient: {target}")\n'
    '        result = execute_command(command)\n'
    '        logger.info(f"📊 rpcclient completed for {target}")\n'
    '        return jsonify(result)',
    '        if not _validate_target(target):\n'
    '            return jsonify({"error": "invalid target"}), 400\n\n'
    '        # Write command sequence to temp file for stdin (avoids shell injection via echo pipe)\n'
    '        import tempfile as _tf, subprocess as _subp2\n'
    '        _cmd_seq = commands.replace(";", "\\n")\n'
    '        with _tf.NamedTemporaryFile(mode="w", suffix=".txt", delete=False) as _tf_obj:\n'
    '            _tf_obj.write(_cmd_seq)\n'
    '            _tf_path = _tf_obj.name\n\n'
    '        rpc_cmd: list[str] = ["rpcclient"]\n'
    '        if username and password:\n'
    '            rpc_cmd += ["-U", f"{username}%{password}"]\n'
    '        elif username:\n'
    '            rpc_cmd += ["-U", username]\n'
    '        else:\n'
    '            rpc_cmd += ["-U", ""]\n'
    '        if domain:\n'
    '            rpc_cmd += ["-W", domain]\n'
    '        rpc_cmd.append(target)\n\n'
    '        try:\n'
    '            with open(_tf_path) as _stdin_f2:\n'
    '                _proc2 = _subp2.run(rpc_cmd, stdin=_stdin_f2, capture_output=True, text=True, timeout=120)\n'
    '            result = {"success": _proc2.returncode == 0, "output": _proc2.stdout, "error": _proc2.stderr, "return_code": _proc2.returncode}\n'
    '        except Exception as _e2:\n'
    '            result = {"success": False, "output": "", "error": str(_e2), "return_code": -1}\n'
    '        finally:\n'
    '            import os as _os; _os.unlink(_tf_path)\n\n'
    '        logger.info("Starting rpcclient: %s", target)\n'
    '        logger.info("rpcclient completed for %s", target)\n'
    '        return jsonify(result)'
))

# --- nbtscan ---
patches.append((
    '        command = f"nbtscan -t {timeout}"\n\n'
    '        if verbose:\n'
    '            command += " -v"\n\n'
    '        command += f" {target}"\n\n'
    '        if additional_args:\n'
    '            command += f" {additional_args}"\n\n'
    '        logger.info(f"🔍 Starting nbtscan: {target}")\n'
    '        result = execute_command(command)\n'
    '        logger.info(f"📊 nbtscan completed for {target}")\n'
    '        return jsonify(result)',
    '        if not _validate_target(target):\n'
    '            return jsonify({"error": "invalid target"}), 400\n'
    '        if additional_args and _SHELL_META_RE.search(additional_args):\n'
    '            return jsonify({"error": "invalid additional_args"}), 400\n\n'
    '        cmd: list[str] = ["nbtscan", "-t", str(timeout)]\n'
    '        if verbose:\n'
    '            cmd.append("-v")\n'
    '        cmd.append(target)\n'
    '        if additional_args:\n'
    '            cmd += additional_args.split()\n\n'
    '        logger.info("Starting nbtscan: %s", target)\n'
    '        result = execute_command(cmd)\n'
    '        logger.info("nbtscan completed for %s", target)\n'
    '        return jsonify(result)'
))

# --- arp-scan ---
patches.append((
    '        command = f"arp-scan -t {timeout} -r {retry}"\n\n'
    '        if interface:\n'
    '            command += f" -I {interface}"\n\n'
    '        if local_network:\n'
    '            command += " -l"\n'
    '        else:\n'
    '            command += f" {target}"\n\n'
    '        if additional_args:\n'
    '            command += f" {additional_args}"\n\n'
    '        logger.info(f"🔍 Starting arp-scan: {target if target else \'local network\'}")\n'
    '        result = execute_command(command)\n'
    '        logger.info(f"📊 arp-scan completed")\n'
    '        return jsonify(result)',
    '        if target and not _validate_target(target):\n'
    '            return jsonify({"error": "invalid target"}), 400\n'
    '        if additional_args and _SHELL_META_RE.search(additional_args):\n'
    '            return jsonify({"error": "invalid additional_args"}), 400\n\n'
    '        cmd: list[str] = ["arp-scan", "-t", str(timeout), "-r", str(retry)]\n'
    '        if interface:\n'
    '            cmd += ["-I", interface]\n'
    '        if local_network:\n'
    '            cmd.append("-l")\n'
    '        elif target:\n'
    '            cmd.append(target)\n'
    '        if additional_args:\n'
    '            cmd += additional_args.split()\n\n'
    '        logger.info("Starting arp-scan: %s", target if target else "local network")\n'
    '        result = execute_command(cmd)\n'
    '        logger.info("arp-scan completed")\n'
    '        return jsonify(result)'
))

# --- responder ---
patches.append((
    '        command = f"timeout {duration} responder -I {interface}"\n\n'
    '        if analyze:\n'
    '            command += " -A"\n\n'
    '        if wpad:\n'
    '            command += " -w"\n\n'
    '        if force_wpad_auth:\n'
    '            command += " -F"\n\n'
    '        if fingerprint:\n'
    '            command += " -f"\n\n'
    '        if additional_args:\n'
    '            command += f" {additional_args}"\n\n'
    '        logger.info(f"🔍 Starting Responder on interface: {interface}")\n'
    '        result = execute_command(command)\n'
    '        logger.info(f"📊 Responder completed")\n'
    '        return jsonify(result)',
    '        if _SHELL_META_RE.search(interface):\n'
    '            return jsonify({"error": "invalid interface"}), 400\n'
    '        if additional_args and _SHELL_META_RE.search(additional_args):\n'
    '            return jsonify({"error": "invalid additional_args"}), 400\n\n'
    '        cmd: list[str] = ["timeout", str(int(duration)), "responder", "-I", interface]\n'
    '        if analyze:\n'
    '            cmd.append("-A")\n'
    '        if wpad:\n'
    '            cmd.append("-w")\n'
    '        if force_wpad_auth:\n'
    '            cmd.append("-F")\n'
    '        if fingerprint:\n'
    '            cmd.append("-f")\n'
    '        if additional_args:\n'
    '            cmd += additional_args.split()\n\n'
    '        logger.info("Starting Responder on interface: %s", interface)\n'
    '        result = execute_command(cmd)\n'
    '        logger.info("Responder completed")\n'
    '        return jsonify(result)'
))

for old, new in patches:
    if old not in content:
        print(f"NOT FOUND: {repr(old[:80])}")
    else:
        content = content.replace(old, new, 1)
        print(f"Patched OK")

with open('hexstrike_server.py', 'w', encoding='utf-8') as f:
    f.write(content)
print("Batch 4b done")
