with open('hexstrike_server.py', encoding='utf-8') as f:
    content = f.read()

patches = []

# --- ghidra ---
patches.append((
    '        command = f"analyzeHeadless {project_dir} {project_name} -import {binary} -deleteProject"\n\n'
    '        if script_file:\n'
    '            command += f" -postScript {script_file}"\n\n'
    '        if output_format == "xml":\n'
    '            command += f" -postScript ExportXml.java {project_dir}/analysis.xml"\n\n'
    '        if additional_args:\n'
    '            command += f" {additional_args}"\n\n'
    '        logger.info(f"🔧 Starting Ghidra analysis: {binary}")\n'
    '        result = execute_command(command, timeout=analysis_timeout)\n'
    '        logger.info(f"📊 Ghidra analysis completed for {binary}")\n'
    '        return jsonify(result)',
    '        if not _validate_path(binary):\n'
    '            return jsonify({"error": "invalid binary"}), 400\n'
    '        if not _validate_path(project_dir):\n'
    '            return jsonify({"error": "invalid project_dir"}), 400\n'
    '        if script_file and not _validate_path(script_file):\n'
    '            return jsonify({"error": "invalid script_file"}), 400\n'
    '        if additional_args and _SHELL_META_RE.search(additional_args):\n'
    '            return jsonify({"error": "invalid additional_args"}), 400\n\n'
    '        cmd: list[str] = ["analyzeHeadless", project_dir, project_name, "-import", binary, "-deleteProject"]\n'
    '        if script_file:\n'
    '            cmd += ["-postScript", script_file]\n'
    '        if output_format == "xml":\n'
    '            cmd += ["-postScript", "ExportXml.java", f"{project_dir}/analysis.xml"]\n'
    '        if additional_args:\n'
    '            cmd += additional_args.split()\n\n'
    '        logger.info("Starting Ghidra analysis: %s", binary)\n'
    '        result = execute_command(cmd)\n'
    '        logger.info("Ghidra analysis completed for %s", binary)\n'
    '        return jsonify(result)'
))

# --- pwntools (script_file already written — just fix command line) ---
patches.append((
    '        command = f"python3 {script_file}"\n\n'
    '        if additional_args:\n'
    '            command += f" {additional_args}"\n\n'
    '        logger.info(f"🔧 Starting Pwntools exploit: {exploit_type}")\n'
    '        result = execute_command(command)\n\n'
    '        # Cleanup\n'
    '        try:\n'
    '            os.remove(script_file)\n'
    '        except:\n'
    '            pass\n\n'
    '        logger.info(f"📊 Pwntools exploit completed")\n'
    '        return jsonify(result)',
    '        if additional_args and _SHELL_META_RE.search(additional_args):\n'
    '            return jsonify({"error": "invalid additional_args"}), 400\n\n'
    '        cmd: list[str] = ["python3", script_file]\n'
    '        if additional_args:\n'
    '            cmd += additional_args.split()\n\n'
    '        logger.info("Starting Pwntools exploit: %s", exploit_type)\n'
    '        result = execute_command(cmd)\n\n'
    '        # Cleanup\n'
    '        try:\n'
    '            os.remove(script_file)\n'
    '        except:\n'
    '            pass\n\n'
    '        logger.info("Pwntools exploit completed")\n'
    '        return jsonify(result)'
))

# --- one-gadget ---
patches.append((
    '        command = f"one_gadget {libc_path} --level {level}"\n\n'
    '        if additional_args:\n'
    '            command += f" {additional_args}"\n\n'
    '        logger.info(f"🔧 Starting one_gadget analysis: {libc_path}")\n'
    '        result = execute_command(command)\n'
    '        logger.info(f"📊 one_gadget analysis completed")\n'
    '        return jsonify(result)',
    '        if not _validate_path(libc_path):\n'
    '            return jsonify({"error": "invalid libc_path"}), 400\n'
    '        if additional_args and _SHELL_META_RE.search(additional_args):\n'
    '            return jsonify({"error": "invalid additional_args"}), 400\n\n'
    '        cmd: list[str] = ["one_gadget", libc_path, "--level", str(level)]\n'
    '        if additional_args:\n'
    '            cmd += additional_args.split()\n\n'
    '        logger.info("Starting one_gadget analysis: %s", libc_path)\n'
    '        result = execute_command(cmd)\n'
    '        logger.info("one_gadget analysis completed")\n'
    '        return jsonify(result)'
))

# --- libc-database (complex — uses shell &&, replace with subprocess chdir) ---
patches.append((
    '        # Navigate to libc-database directory (assuming it\'s installed)\n'
    '        base_command = "cd /opt/libc-database 2>/dev/null || cd ~/libc-database 2>/dev/null || echo \'libc-database not found\'"\n\n'
    '        if action == "find":\n'
    '            command = f"{base_command} && ./find {symbols}"\n'
    '        elif action == "dump":\n'
    '            command = f"{base_command} && ./dump {libc_id}"\n'
    '        elif action == "download":\n'
    '            command = f"{base_command} && ./download {libc_id}"\n'
    '        else:\n'
    '            return jsonify({"error": f"Invalid action: {action}"}), 400\n\n'
    '        if additional_args:\n'
    '            command += f" {additional_args}"\n\n'
    '        logger.info(f"🔧 Starting libc-database {action}: {symbols or libc_id}")\n'
    '        result = execute_command(command)\n'
    '        logger.info(f"📊 libc-database {action} completed")\n'
    '        return jsonify(result)',
    '        _VALID_ACTIONS = {"find", "dump", "download"}\n'
    '        if action not in _VALID_ACTIONS:\n'
    '            return jsonify({"error": f"Invalid action: {action}"}), 400\n'
    '        if symbols and _SHELL_META_RE.search(symbols):\n'
    '            return jsonify({"error": "invalid symbols"}), 400\n'
    '        if libc_id and _SHELL_META_RE.search(libc_id):\n'
    '            return jsonify({"error": "invalid libc_id"}), 400\n\n'
    '        # Find libc-database directory\n'
    '        import os as _os2\n'
    '        _db_dir = "/opt/libc-database" if _os2.path.isdir("/opt/libc-database") else _os2.path.expanduser("~/libc-database")\n'
    '        if action == "find":\n'
    '            cmd: list[str] = [f"{_db_dir}/find"] + symbols.split()\n'
    '        elif action == "dump":\n'
    '            cmd = [f"{_db_dir}/dump", libc_id]\n'
    '        else:\n'
    '            cmd = [f"{_db_dir}/download", libc_id]\n\n'
    '        import subprocess as _subp3\n'
    '        try:\n'
    '            _pr = _subp3.run(cmd, capture_output=True, text=True, timeout=120, cwd=_db_dir)\n'
    '            result = {"success": _pr.returncode == 0, "output": _pr.stdout, "error": _pr.stderr, "return_code": _pr.returncode}\n'
    '        except Exception as _e3:\n'
    '            result = {"success": False, "output": "", "error": str(_e3), "return_code": -1}\n\n'
    '        logger.info("Starting libc-database %s: %s", action, symbols or libc_id)\n'
    '        logger.info("libc-database %s completed", action)\n'
    '        return jsonify(result)'
))

# --- gdb-peda ---
patches.append((
    '        # Base GDB command with PEDA\n'
    '        command = "gdb -q"\n\n'
    '        if binary:\n'
    '            command += f" {binary}"\n\n'
    '        if core_file:\n'
    '            command += f" {core_file}"\n\n'
    '        if attach_pid:\n'
    '            command += f" -p {attach_pid}"\n\n'
    '        # Create command script\n'
    '        if commands:\n'
    '            temp_script = "/tmp/gdb_peda_commands.txt"\n'
    '            peda_commands = f"""\nsource ~/peda/peda.py\n{commands}\nquit\n"""\n'
    '            with open(temp_script, "w") as f:\n'
    '                f.write(peda_commands)\n'
    '            command += f" -x {temp_script}"\n'
    '        else:\n'
    "            # Default PEDA initialization\n"
    "            command += \" -ex 'source ~/peda/peda.py' -ex 'quit'\"\n\n"
    '        if additional_args:\n'
    '            command += f" {additional_args}"\n\n'
    "        target_info = binary or f'PID {attach_pid}' or core_file\n"
    '        logger.info(f"🔧 Starting GDB-PEDA analysis: {target_info}")\n'
    '        result = execute_command(command)\n\n'
    '        # Cleanup\n'
    '        if commands and os.path.exists("/tmp/gdb_peda_commands.txt"):\n'
    '            try:\n'
    '                os.remove("/tmp/gdb_peda_commands.txt")\n'
    '            except:\n'
    '                pass\n\n'
    '        logger.info(f"📊 GDB-PEDA analysis completed")\n'
    '        return jsonify(result)',
    '        if binary and not _validate_path(binary):\n'
    '            return jsonify({"error": "invalid binary"}), 400\n'
    '        if core_file and not _validate_path(core_file):\n'
    '            return jsonify({"error": "invalid core_file"}), 400\n\n'
    '        cmd: list[str] = ["gdb", "-q"]\n'
    '        if binary:\n'
    '            cmd.append(binary)\n'
    '        if core_file:\n'
    '            cmd.append(core_file)\n'
    '        if attach_pid:\n'
    '            cmd += ["-p", str(attach_pid)]\n'
    '        if commands:\n'
    '            temp_script = "/tmp/gdb_peda_commands.txt"\n'
    '            with open(temp_script, "w") as f:\n'
    '                f.write(f"source ~/peda/peda.py\\n{commands}\\nquit\\n")\n'
    '            cmd += ["-x", temp_script]\n'
    '        else:\n'
    '            cmd += ["-ex", "source ~/peda/peda.py", "-ex", "quit"]\n\n'
    '        target_info = binary or f"PID {attach_pid}" or core_file\n'
    '        logger.info("Starting GDB-PEDA analysis: %s", target_info)\n'
    '        result = execute_command(cmd)\n\n'
    '        if commands and os.path.exists("/tmp/gdb_peda_commands.txt"):\n'
    '            try:\n'
    '                os.remove("/tmp/gdb_peda_commands.txt")\n'
    '            except:\n'
    '                pass\n\n'
    '        logger.info("GDB-PEDA analysis completed")\n'
    '        return jsonify(result)'
))

# --- ropper ---
patches.append((
    '        command = f"ropper --file {binary}"\n\n'
    '        if gadget_type == "rop":\n'
    '            command += " --rop"\n'
    '        elif gadget_type == "jop":\n'
    '            command += " --jop"\n'
    '        elif gadget_type == "sys":\n'
    '            command += " --sys"\n'
    '        elif gadget_type == "all":\n'
    '            command += " --all"\n\n'
    '        if quality > 1:\n'
    '            command += f" --quality {quality}"\n\n'
    '        if arch:\n'
    '            command += f" --arch {arch}"\n\n'
    '        if search_string:\n'
    "            command += f\" --search '{search_string}'\"\n\n"
    '        if additional_args:\n'
    '            command += f" {additional_args}"\n\n'
    '        logger.info(f"🔧 Starting ropper analysis: {binary}")\n'
    '        result = execute_command(command)\n'
    '        logger.info(f"📊 ropper analysis completed")\n'
    '        return jsonify(result)',
    '        if not _validate_path(binary):\n'
    '            return jsonify({"error": "invalid binary"}), 400\n'
    '        if additional_args and _SHELL_META_RE.search(additional_args):\n'
    '            return jsonify({"error": "invalid additional_args"}), 400\n\n'
    '        cmd: list[str] = ["ropper", "--file", binary]\n'
    '        if gadget_type == "rop":\n'
    '            cmd.append("--rop")\n'
    '        elif gadget_type == "jop":\n'
    '            cmd.append("--jop")\n'
    '        elif gadget_type == "sys":\n'
    '            cmd.append("--sys")\n'
    '        elif gadget_type == "all":\n'
    '            cmd.append("--all")\n'
    '        if quality > 1:\n'
    '            cmd += ["--quality", str(quality)]\n'
    '        if arch:\n'
    '            cmd += ["--arch", arch]\n'
    '        if search_string and not _SHELL_META_RE.search(search_string):\n'
    '            cmd += ["--search", search_string]\n'
    '        if additional_args:\n'
    '            cmd += additional_args.split()\n\n'
    '        logger.info("Starting ropper analysis: %s", binary)\n'
    '        result = execute_command(cmd)\n'
    '        logger.info("ropper analysis completed")\n'
    '        return jsonify(result)'
))

# --- pwninit ---
patches.append((
    '        command = f"pwninit --bin {binary}"\n\n'
    '        if libc:\n'
    '            command += f" --libc {libc}"\n\n'
    '        if ld:\n'
    '            command += f" --ld {ld}"\n\n'
    '        if template_type:\n'
    '            command += f" --template {template_type}"\n\n'
    '        if additional_args:\n'
    '            command += f" {additional_args}"\n\n'
    '        logger.info(f"🔧 Starting pwninit setup: {binary}")\n'
    '        result = execute_command(command)\n'
    '        logger.info(f"📊 pwninit setup completed")\n'
    '        return jsonify(result)',
    '        if not _validate_path(binary):\n'
    '            return jsonify({"error": "invalid binary"}), 400\n'
    '        if libc and not _validate_path(libc):\n'
    '            return jsonify({"error": "invalid libc"}), 400\n'
    '        if ld and not _validate_path(ld):\n'
    '            return jsonify({"error": "invalid ld"}), 400\n'
    '        if additional_args and _SHELL_META_RE.search(additional_args):\n'
    '            return jsonify({"error": "invalid additional_args"}), 400\n\n'
    '        cmd: list[str] = ["pwninit", "--bin", binary]\n'
    '        if libc:\n'
    '            cmd += ["--libc", libc]\n'
    '        if ld:\n'
    '            cmd += ["--ld", ld]\n'
    '        if template_type:\n'
    '            cmd += ["--template", template_type]\n'
    '        if additional_args:\n'
    '            cmd += additional_args.split()\n\n'
    '        logger.info("Starting pwninit setup: %s", binary)\n'
    '        result = execute_command(cmd)\n'
    '        logger.info("pwninit setup completed")\n'
    '        return jsonify(result)'
))

for old, new in patches:
    if old not in content:
        print(f"NOT FOUND: {repr(old[:80])}")
    else:
        content = content.replace(old, new, 1)
        print(f"Patched OK")

with open('hexstrike_server.py', 'w', encoding='utf-8') as f:
    f.write(content)
print("Batch 6 done")
